version: '3.8'

services:
  # Eureka Server
  eureka-server:
    image: springcloud/demo-eureka-server
    container_name: eureka-server
    ports:
      - "8771:8761"
    networks:
      - microservices

  # PostgreSQL for users service
  postgres-users:
    image: postgres:latest
    container_name: postgres-users
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qawsed?
    ports:
      - "5431:5432"
    networks:
      - microservices

  # PostgreSQL for products service
  postgres-products:
    image: postgres:latest
    container_name: postgres-products
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qawsed?
    ports:
      - "5432:5432"
    networks:
      - microservices

  # PostgreSQL for orders service
  postgres-orders:
    image: postgres:latest
    container_name: postgres-orders
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qawsed?
    ports:
      - "5433:5432"
    networks:
      - microservices

  # Users microservice
  users-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: users-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-users:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qawsed?
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres-users
      - eureka-server
    networks:
      - microservices

  # Products microservice
  products-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: products-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-products:5432/productdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qawsed?
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres-products
      - eureka-server
    networks:
      - microservices

  # Orders microservice
  orders-service:
    build:
      context: ./orderservice
      dockerfile: Dockerfile
    container_name: orders-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-orders:5432/orderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qawsed?
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres-orders
      - eureka-server
    networks:
      - microservices

  # Gateway service
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    environment:
      SPRING_APPLICATION_NAME: gateway-service
      SERVER_PORT: 8089
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8090:8089"
    depends_on:
      - eureka-server
    networks:
      - microservices

  # Prometheus

networks:
  microservices:
    driver: bridge


